CREATE TABLE `actividad_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fecha` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id` int DEFAULT NULL,
  `usuario_nombre` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Sistema',
  `usuario_rol` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sistema',
  `accion` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entidad` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entidad_id` int DEFAULT NULL,
  `descripcion` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `detalle` json DEFAULT NULL,
  `ip` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_activ_fecha` (`fecha`),
  KEY `idx_activ_usuario` (`usuario_id`),
  KEY `idx_activ_accion` (`accion`),
  KEY `idx_activ_entidad` (`entidad`,`entidad_id`)
) ENGINE=InnoDB AUTO_INCREMENT=317 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cliente_operadores` (
  `cliente_id` int NOT NULL,
  `usuario_id` int NOT NULL,
  PRIMARY KEY (`cliente_id`,`usuario_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `clientes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre_empresa` varchar(150) NOT NULL,
  `contacto` varchar(100) DEFAULT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `direccion` text,
  `fecha_creacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `activo` tinyint(1) DEFAULT '1',
  `prefijo_tracking` varchar(10) NOT NULL DEFAULT 'TRK',
  `ultimo_numero_tracking` int unsigned NOT NULL DEFAULT '0',
  `eliminado_en` datetime DEFAULT NULL,
  `template_etiqueta_id` int DEFAULT NULL,
  `template_guia_id` int DEFAULT NULL,
  `metodo_pago_defecto` varchar(3) NOT NULL DEFAULT 'PPD',
  `habilitado` tinyint(1) NOT NULL DEFAULT '1',
  `logo_url` varchar(500) DEFAULT NULL,
  `ocultar_fecha` tinyint(1) NOT NULL DEFAULT '0',
  `ocultar_hora` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_prefijo_tracking` (`prefijo_tracking`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `configuracion_sistema` (
  `id` int NOT NULL AUTO_INCREMENT,
  `clave` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `valor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `tipo` enum('texto','numero','boolean','json') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'texto',
  `categoria` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `descripcion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `fecha_modificacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modificado_por` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `clave` (`clave`),
  KEY `modificado_por` (`modificado_por`),
  CONSTRAINT `configuracion_sistema_ibfk_1` FOREIGN KEY (`modificado_por`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=269 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `direcciones_cliente` (
  `id` int NOT NULL AUTO_INCREMENT,
  `cliente_id` int NOT NULL,
  `alias` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre descriptivo: Bodega Principal, Sucursal Centro, etc.',
  `tipo` enum('origen','destino','ambos') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ambos',
  `calle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `colonia` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ciudad` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `estado` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `cp` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `referencia` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `es_predeterminada` tinyint(1) DEFAULT '0' COMMENT 'Dirección por defecto para este cliente',
  `activa` tinyint(1) DEFAULT '1',
  `fecha_creacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_cliente_id` (`cliente_id`),
  KEY `idx_tipo` (`tipo`),
  KEY `idx_activa` (`activa`),
  CONSTRAINT `direcciones_cliente_ibfk_1` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Direcciones frecuentes guardadas por cliente';

CREATE TABLE `direcciones_empresa` (
  `id` int NOT NULL AUTO_INCREMENT,
  `alias` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre descriptivo: Bodega Central, Almacén Norte, etc.',
  `tipo` enum('origen','destino','ambos') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'origen',
  `calle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `colonia` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ciudad` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `estado` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `cp` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `referencia` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `es_predeterminada` tinyint(1) DEFAULT '0' COMMENT 'Dirección predeterminada para nuevos envíos',
  `activa` tinyint(1) DEFAULT '1',
  `fecha_creacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_alias_unico` (`alias`),
  KEY `idx_activa` (`activa`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Direcciones de la empresa desde donde se originan envíos';

CREATE TABLE `envio_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `envio_id` int NOT NULL,
  `cantidad` int NOT NULL DEFAULT '1',
  `tipo` varchar(100) NOT NULL,
  `descripcion` varchar(255) DEFAULT NULL,
  `peso` decimal(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  KEY `envio_id` (`envio_id`),
  CONSTRAINT `envio_items_ibfk_1` FOREIGN KEY (`envio_id`) REFERENCES `envios` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `envio_pictogramas` (
  `envio_id` int NOT NULL,
  `pictograma_id` int NOT NULL,
  PRIMARY KEY (`envio_id`,`pictograma_id`),
  KEY `fk_ep_picto` (`pictograma_id`),
  CONSTRAINT `fk_ep_envio_new` FOREIGN KEY (`envio_id`) REFERENCES `envios` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ep_picto_new` FOREIGN KEY (`pictograma_id`) REFERENCES `pictogramas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `envios` (
  `id` int NOT NULL AUTO_INCREMENT,
  `numero_tracking` varchar(50) NOT NULL,
  `referencia_cliente` varchar(100) DEFAULT NULL,
  `cliente_id` int DEFAULT NULL,
  `cliente_nombre` varchar(255) DEFAULT NULL,
  `origen` varchar(200) NOT NULL,
  `destino` varchar(200) NOT NULL,
  `origen_calle` varchar(255) DEFAULT NULL,
  `origen_colonia` varchar(100) DEFAULT NULL,
  `origen_ciudad` varchar(100) DEFAULT NULL,
  `origen_estado` varchar(50) DEFAULT NULL,
  `origen_cp` varchar(5) DEFAULT NULL,
  `origen_referencia` varchar(255) DEFAULT NULL,
  `destino_calle` varchar(255) DEFAULT NULL,
  `destino_colonia` varchar(100) DEFAULT NULL,
  `destino_ciudad` varchar(100) DEFAULT NULL,
  `destino_estado` varchar(50) DEFAULT NULL,
  `destino_cp` varchar(5) DEFAULT NULL,
  `destino_referencia` varchar(255) DEFAULT NULL,
  `descripcion` text,
  `peso` decimal(10,2) DEFAULT NULL,
  `estado_actual` varchar(50) DEFAULT 'creado',
  `fecha_creacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_estimada_entrega` date DEFAULT NULL,
  `usuario_creador_id` int DEFAULT NULL,
  `es_parcial` tinyint(1) NOT NULL DEFAULT '0',
  `envio_relacionado_id` int DEFAULT NULL,
  `es_complemento` tinyint(1) NOT NULL DEFAULT '0',
  `numero_parte` int DEFAULT NULL,
  `etiqueta_modificada` tinyint(1) NOT NULL DEFAULT '0',
  `metodo_pago` varchar(3) NOT NULL DEFAULT 'PPD',
  `documentar_nombre` varchar(200) DEFAULT NULL,
  `documentar_calle` varchar(200) DEFAULT NULL,
  `documentar_colonia` varchar(150) DEFAULT NULL,
  `documentar_cp` varchar(10) DEFAULT NULL,
  `documentar_ciudad` varchar(150) DEFAULT NULL,
  `documentar_estado` varchar(100) DEFAULT NULL,
  `documentar_referencia` varchar(200) DEFAULT NULL,
  `editado_por_nombre` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `numero_tracking` (`numero_tracking`),
  KEY `cliente_id` (`cliente_id`),
  KEY `usuario_creador_id` (`usuario_creador_id`),
  KEY `idx_numero_tracking` (`numero_tracking`),
  KEY `fk_envio_relacionado` (`envio_relacionado_id`),
  CONSTRAINT `envios_ibfk_1` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`),
  CONSTRAINT `envios_ibfk_2` FOREIGN KEY (`usuario_creador_id`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `fk_envio_relacionado` FOREIGN KEY (`envio_relacionado_id`) REFERENCES `envios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `etiqueta_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `mostrar_logo` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_eslogan` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_telefono` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_telefono_adicional` tinyint(1) NOT NULL DEFAULT '0',
  `mostrar_email` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_sitio_web` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_rfc` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_direccion_fiscal` tinyint(1) NOT NULL DEFAULT '0',
  `mostrar_barcode` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_qr` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_ruta` tinyint(1) NOT NULL DEFAULT '1',
  `mostrar_descripcion` tinyint(1) NOT NULL DEFAULT '1',
  `obligatorio_logo` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_eslogan` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_telefono` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_telefono_adicional` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_email` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_sitio_web` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_rfc` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_direccion_fiscal` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_barcode` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_qr` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_ruta` tinyint(1) NOT NULL DEFAULT '0',
  `obligatorio_descripcion` tinyint(1) NOT NULL DEFAULT '0',
  `creado_por` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `mostrar_dest_nombre` tinyint(1) DEFAULT '1',
  `mostrar_dest_direccion` tinyint(1) DEFAULT '1',
  `obligatorio_dest_direccion` tinyint(1) DEFAULT '0',
  `obligatorio_dest_referencia` tinyint(1) DEFAULT '0',
  `obligatorio_dest_nombre` tinyint(1) DEFAULT '0',
  `mostrar_dest_referencia` tinyint(1) DEFAULT '1',
  `mostrar_dest_contacto` tinyint(1) DEFAULT '1',
  `mostrar_dest_telefono` tinyint(1) DEFAULT '1',
  `obligatorio_dest_contacto` tinyint(1) DEFAULT '0',
  `obligatorio_dest_telefono` tinyint(1) DEFAULT '0',
  `texto_entregar_a` varchar(100) DEFAULT NULL,
  `texto_peso` varchar(50) DEFAULT NULL,
  `texto_entrega_estimada` varchar(100) DEFAULT NULL,
  `texto_ref_cliente` varchar(100) DEFAULT NULL,
  `texto_descripcion` varchar(100) DEFAULT NULL,
  `texto_fecha_emision` varchar(100) DEFAULT NULL,
  `texto_etiqueta` varchar(50) DEFAULT NULL,
  `size_tracking` tinyint unsigned DEFAULT NULL,
  `size_ruta_ciudad` tinyint unsigned DEFAULT NULL,
  `size_dest_nombre` tinyint unsigned DEFAULT NULL,
  `size_dest_direccion` tinyint unsigned DEFAULT NULL,
  `size_empresa_nombre` tinyint unsigned DEFAULT NULL,
  `size_eslogan` tinyint unsigned DEFAULT NULL,
  `size_tipo_servicio` tinyint unsigned DEFAULT NULL,
  `size_detalle_valor` tinyint unsigned DEFAULT NULL,
  `size_descripcion` tinyint unsigned DEFAULT NULL,
  `size_dest_contacto` tinyint unsigned DEFAULT NULL,
  `size_barra_contacto` tinyint unsigned DEFAULT NULL,
  `size_ruta_etiqueta` tinyint unsigned DEFAULT NULL,
  `size_detalle_etiqueta` tinyint unsigned DEFAULT NULL,
  `size_cab_fecha` tinyint unsigned DEFAULT NULL,
  `size_cab_num` tinyint unsigned DEFAULT NULL,
  `mostrar_alias_ruta` tinyint(1) DEFAULT '0',
  `obligatorio_alias_ruta` tinyint(1) DEFAULT '0',
  `mostrar_peso_total` tinyint(1) DEFAULT '1',
  `obligatorio_peso_total` tinyint(1) DEFAULT '0',
  `mostrar_peso_item` tinyint(1) DEFAULT '0',
  `obligatorio_peso_item` tinyint(1) DEFAULT '0',
  `texto_peso_item` varchar(50) DEFAULT NULL,
  `bloqueado` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `etiquetas_config_impresa` (
  `id` int NOT NULL AUTO_INCREMENT,
  `envio_id` int NOT NULL,
  `mostrar_logo` tinyint(1) DEFAULT '1',
  `mostrar_eslogan` tinyint(1) DEFAULT '1',
  `mostrar_telefono` tinyint(1) DEFAULT '1',
  `mostrar_telefono_adicional` tinyint(1) DEFAULT '1',
  `mostrar_email` tinyint(1) DEFAULT '1',
  `mostrar_sitio_web` tinyint(1) DEFAULT '1',
  `mostrar_rfc` tinyint(1) DEFAULT '1',
  `mostrar_direccion_fiscal` tinyint(1) DEFAULT '1',
  `mostrar_barcode` tinyint(1) DEFAULT '1',
  `mostrar_qr` tinyint(1) DEFAULT '1',
  `mostrar_ruta` tinyint(1) DEFAULT '1',
  `mostrar_descripcion` tinyint(1) DEFAULT '1',
  `mostrar_dest_nombre` tinyint(1) DEFAULT '1',
  `mostrar_dest_direccion` tinyint(1) DEFAULT '1',
  `mostrar_dest_referencia` tinyint(1) DEFAULT '1',
  `mostrar_dest_contacto` tinyint(1) DEFAULT '1',
  `mostrar_dest_telefono` tinyint(1) DEFAULT '1',
  `mostrar_alias_ruta` tinyint(1) DEFAULT '0',
  `mostrar_peso_total` tinyint(1) DEFAULT '1',
  `mostrar_peso_item` tinyint(1) DEFAULT '0',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `checksum` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `primera_impresion` timestamp NULL DEFAULT NULL,
  `veces_impresa` int NOT NULL DEFAULT '1',
  `ultimo_usuario` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activa` tinyint(1) NOT NULL DEFAULT '1',
  `presentado_portal` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fotos_evidencia` (
  `id` int NOT NULL AUTO_INCREMENT,
  `historial_estado_id` int NOT NULL,
  `url_foto` varchar(500) NOT NULL,
  `descripcion` text,
  `fecha_subida` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `historial_estado_id` (`historial_estado_id`),
  CONSTRAINT `fotos_evidencia_ibfk_1` FOREIGN KEY (`historial_estado_id`) REFERENCES `historial_estados` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `guia_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `mostrar_logo` tinyint(1) DEFAULT '1',
  `mostrar_rfc` tinyint(1) DEFAULT '1',
  `mostrar_telefono` tinyint(1) DEFAULT '1',
  `mostrar_sitio_web` tinyint(1) DEFAULT '1',
  `mostrar_barcode` tinyint(1) DEFAULT '1',
  `mostrar_seccion_remitente` tinyint(1) DEFAULT '1',
  `mostrar_seccion_facturar` tinyint(1) DEFAULT '1',
  `mostrar_seccion_destinatario` tinyint(1) DEFAULT '1',
  `mostrar_clausula_seguro` tinyint(1) DEFAULT '1',
  `mostrar_retorno_documentos` tinyint(1) DEFAULT '1',
  `mostrar_condiciones_pago` tinyint(1) DEFAULT '1',
  `mostrar_fecha_emision` tinyint(1) DEFAULT '1',
  `mostrar_observaciones` tinyint(1) DEFAULT '1',
  `mostrar_fecha_entrega` tinyint(1) DEFAULT '1',
  `mostrar_referencia_cliente` tinyint(1) DEFAULT '1',
  `mostrar_recibido_por` tinyint(1) DEFAULT '1',
  `mostrar_operador` tinyint(1) DEFAULT '1',
  `mostrar_firma_final` tinyint(1) DEFAULT '1',
  `mostrar_pie_datos` tinyint(1) DEFAULT '1',
  `mostrar_disclaimer` tinyint(1) DEFAULT '1',
  `mostrar_col_volumen` tinyint(1) DEFAULT '1',
  `mostrar_col_peso_facturado` tinyint(1) DEFAULT '1',
  `mostrar_col_servicios` tinyint(1) DEFAULT '1',
  `mostrar_col_importe` tinyint(1) DEFAULT '1',
  `obligatorio_logo` tinyint(1) DEFAULT '0',
  `obligatorio_rfc` tinyint(1) DEFAULT '0',
  `obligatorio_telefono` tinyint(1) DEFAULT '0',
  `obligatorio_sitio_web` tinyint(1) DEFAULT '0',
  `obligatorio_barcode` tinyint(1) DEFAULT '0',
  `obligatorio_seccion_remitente` tinyint(1) DEFAULT '0',
  `obligatorio_seccion_facturar` tinyint(1) DEFAULT '0',
  `obligatorio_seccion_destinatario` tinyint(1) DEFAULT '0',
  `obligatorio_clausula_seguro` tinyint(1) DEFAULT '0',
  `obligatorio_retorno_documentos` tinyint(1) DEFAULT '0',
  `obligatorio_condiciones_pago` tinyint(1) DEFAULT '0',
  `obligatorio_fecha_emision` tinyint(1) DEFAULT '0',
  `obligatorio_observaciones` tinyint(1) DEFAULT '0',
  `obligatorio_fecha_entrega` tinyint(1) DEFAULT '0',
  `obligatorio_referencia_cliente` tinyint(1) DEFAULT '0',
  `obligatorio_recibido_por` tinyint(1) DEFAULT '0',
  `obligatorio_operador` tinyint(1) DEFAULT '0',
  `obligatorio_firma_final` tinyint(1) DEFAULT '0',
  `obligatorio_pie_datos` tinyint(1) DEFAULT '0',
  `obligatorio_disclaimer` tinyint(1) DEFAULT '0',
  `obligatorio_col_volumen` tinyint(1) DEFAULT '0',
  `obligatorio_col_peso_facturado` tinyint(1) DEFAULT '0',
  `obligatorio_col_servicios` tinyint(1) DEFAULT '0',
  `obligatorio_col_importe` tinyint(1) DEFAULT '0',
  `creado_por` int DEFAULT NULL,
  `creado_en` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `descripcion_servicio` varchar(200) DEFAULT NULL,
  `titulo_guia` varchar(100) DEFAULT NULL,
  `mensaje_1` text,
  `mensaje_2` text,
  `mensaje_3` text,
  `mensaje_4` text,
  `mostrar_facturar_rfc` tinyint(1) DEFAULT '1',
  `mostrar_facturar_direccion` tinyint(1) DEFAULT '1',
  `mostrar_facturar_nombre` tinyint(1) DEFAULT '1',
  `mostrar_remitente_nombre` tinyint(1) DEFAULT '1',
  `mostrar_facturar_contacto` tinyint(1) DEFAULT '1',
  `mostrar_remitente_direccion` tinyint(1) DEFAULT '1',
  `mostrar_facturar_telefono` tinyint(1) DEFAULT '1',
  `mostrar_facturar_email` tinyint(1) DEFAULT '1',
  `mostrar_destinatario_nombre` tinyint(1) DEFAULT '1',
  `mostrar_remitente_telefono` tinyint(1) DEFAULT '1',
  `mostrar_destinatario_direccion` tinyint(1) DEFAULT '1',
  `obligatorio_remitente_nombre` tinyint(1) DEFAULT '0',
  `obligatorio_remitente_direccion` tinyint(1) DEFAULT '0',
  `obligatorio_remitente_telefono` tinyint(1) DEFAULT '0',
  `obligatorio_facturar_nombre` tinyint(1) DEFAULT '0',
  `obligatorio_facturar_direccion` tinyint(1) DEFAULT '0',
  `obligatorio_facturar_contacto` tinyint(1) DEFAULT '0',
  `obligatorio_facturar_telefono` tinyint(1) DEFAULT '0',
  `obligatorio_facturar_email` tinyint(1) DEFAULT '0',
  `obligatorio_facturar_rfc` tinyint(1) DEFAULT '0',
  `obligatorio_destinatario_nombre` tinyint(1) DEFAULT '0',
  `obligatorio_destinatario_direccion` tinyint(1) DEFAULT '0',
  `etiqueta_col_descripcion` varchar(200) DEFAULT NULL COMMENT 'Encabezado columna descripción en tabla de carga',
  `etiqueta_operador` varchar(200) DEFAULT NULL COMMENT 'Etiqueta de la sección Operador que entregó',
  `size_guia_titulo` tinyint unsigned DEFAULT NULL,
  `size_tracking_big` tinyint unsigned DEFAULT NULL,
  `size_company_name` tinyint unsigned DEFAULT NULL,
  `size_seccion_content` tinyint unsigned DEFAULT NULL,
  `size_cargo_td` tinyint unsigned DEFAULT NULL,
  `size_guia_servicio` tinyint unsigned DEFAULT NULL,
  `size_seccion_label` tinyint unsigned DEFAULT NULL,
  `size_cargo_th` tinyint unsigned DEFAULT NULL,
  `size_footer_content` tinyint unsigned DEFAULT NULL,
  `size_pago_big` tinyint unsigned DEFAULT NULL,
  `size_msg_row` tinyint unsigned DEFAULT NULL,
  `height_obs_tall` smallint unsigned DEFAULT NULL,
  `mostrar_obs_operador` tinyint(1) DEFAULT '1',
  `obligatorio_obs_operador` tinyint(1) DEFAULT '0',
  `mostrar_obs_recibido` tinyint(1) DEFAULT '1',
  `obligatorio_obs_recibido` tinyint(1) DEFAULT '0',
  `etiqueta_obs_operador` varchar(200) DEFAULT NULL,
  `etiqueta_recibido_por` varchar(200) DEFAULT NULL,
  `etiqueta_obs_recibido` varchar(200) DEFAULT NULL,
  `bloqueado` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `guias_config_impresa` (
  `id` int NOT NULL AUTO_INCREMENT,
  `envio_id` int NOT NULL,
  `mostrar_logo` tinyint(1) DEFAULT '1',
  `mostrar_rfc` tinyint(1) DEFAULT '1',
  `mostrar_telefono` tinyint(1) DEFAULT '1',
  `mostrar_sitio_web` tinyint(1) DEFAULT '1',
  `mostrar_barcode` tinyint(1) DEFAULT '1',
  `mostrar_seccion_remitente` tinyint(1) DEFAULT '1',
  `mostrar_remitente_nombre` tinyint(1) DEFAULT '1',
  `mostrar_remitente_direccion` tinyint(1) DEFAULT '1',
  `mostrar_remitente_telefono` tinyint(1) DEFAULT '1',
  `mostrar_seccion_facturar` tinyint(1) DEFAULT '1',
  `mostrar_facturar_nombre` tinyint(1) DEFAULT '1',
  `mostrar_facturar_direccion` tinyint(1) DEFAULT '1',
  `mostrar_facturar_contacto` tinyint(1) DEFAULT '1',
  `mostrar_facturar_telefono` tinyint(1) DEFAULT '1',
  `mostrar_facturar_email` tinyint(1) DEFAULT '1',
  `mostrar_facturar_rfc` tinyint(1) DEFAULT '1',
  `mostrar_seccion_destinatario` tinyint(1) DEFAULT '1',
  `mostrar_destinatario_nombre` tinyint(1) DEFAULT '1',
  `mostrar_destinatario_direccion` tinyint(1) DEFAULT '1',
  `mostrar_clausula_seguro` tinyint(1) DEFAULT '1',
  `mostrar_observaciones` tinyint(1) DEFAULT '1',
  `mostrar_condiciones_pago` tinyint(1) DEFAULT '1',
  `mostrar_fecha_emision` tinyint(1) DEFAULT '1',
  `mostrar_fecha_entrega` tinyint(1) DEFAULT '1',
  `mostrar_referencia_cliente` tinyint(1) DEFAULT '1',
  `mostrar_retorno_documentos` tinyint(1) DEFAULT '1',
  `mostrar_operador` tinyint(1) DEFAULT '1',
  `mostrar_obs_operador` tinyint(1) DEFAULT '1',
  `mostrar_recibido_por` tinyint(1) DEFAULT '1',
  `mostrar_obs_recibido` tinyint(1) DEFAULT '1',
  `mostrar_firma_final` tinyint(1) DEFAULT '1',
  `mostrar_col_volumen` tinyint(1) DEFAULT '1',
  `mostrar_col_peso_facturado` tinyint(1) DEFAULT '1',
  `mostrar_col_servicios` tinyint(1) DEFAULT '1',
  `mostrar_col_importe` tinyint(1) DEFAULT '1',
  `mostrar_pie_datos` tinyint(1) DEFAULT '1',
  `mostrar_disclaimer` tinyint(1) DEFAULT '1',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `checksum` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `primera_impresion` timestamp NULL DEFAULT NULL,
  `veces_impresa` int NOT NULL DEFAULT '1',
  `ultimo_usuario` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activa` tinyint(1) NOT NULL DEFAULT '1',
  `presentado_portal` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `historial_estados` (
  `id` int NOT NULL AUTO_INCREMENT,
  `envio_id` int NOT NULL,
  `estado` varchar(50) NOT NULL,
  `ubicacion` varchar(200) DEFAULT NULL,
  `comentarios` text,
  `foto_evidencia` varchar(255) DEFAULT NULL,
  `fecha_hora` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `envio_id` (`envio_id`),
  KEY `usuario_id` (`usuario_id`),
  CONSTRAINT `historial_estados_ibfk_1` FOREIGN KEY (`envio_id`) REFERENCES `envios` (`id`) ON DELETE CASCADE,
  CONSTRAINT `historial_estados_ibfk_2` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `impresiones_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `envio_id` int NOT NULL,
  `tipo` enum('guia','etiqueta') COLLATE utf8mb4_unicode_ci NOT NULL,
  `usuario_id` int DEFAULT NULL,
  `usuario_nombre` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Sistema',
  `fecha` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tuvo_cambios` tinyint(1) NOT NULL DEFAULT '0',
  `desde_portal` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_implog_envio` (`envio_id`,`tipo`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `perfiles_impresora` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ancho_mm` decimal(6,2) NOT NULL DEFAULT '101.60',
  `alto_mm` decimal(6,2) NOT NULL DEFAULT '152.40',
  `margen_top` decimal(4,2) NOT NULL DEFAULT '0.00',
  `margen_bottom` decimal(4,2) NOT NULL DEFAULT '0.00',
  `margen_left` decimal(4,2) NOT NULL DEFAULT '0.00',
  `margen_right` decimal(4,2) NOT NULL DEFAULT '0.00',
  `compactacion` decimal(4,2) NOT NULL DEFAULT '0.00',
  `activo` tinyint(1) NOT NULL DEFAULT '1',
  `creado_por` int DEFAULT NULL,
  `creado_en` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_perfil_impresora_creador` (`creado_por`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pictogramas` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `imagen_url` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `activo` tinyint(1) DEFAULT '1',
  `orden` int DEFAULT '0',
  `creado_por` int DEFAULT NULL,
  `creado_en` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_picto_creador` (`creado_por`),
  CONSTRAINT `picto_ibfk_1` FOREIGN KEY (`creado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tipos_empaques` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `activo` tinyint(1) DEFAULT '1',
  `orden` int DEFAULT '0',
  `creado_en` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tipo_empaque_nombre` (`nombre`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cat├ílogo de tipos de empaque para ├¡tems de env├¡o';

CREATE TABLE `usuario_sucursales` (
  `usuario_id` int NOT NULL,
  `sucursal_dir_id` int NOT NULL,
  PRIMARY KEY (`usuario_id`,`sucursal_dir_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `usuarios` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `rol` enum('admin','operador','cliente','superusuario') DEFAULT 'operador',
  `activo` tinyint(1) DEFAULT '1',
  `fecha_creacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `cliente_id` int DEFAULT NULL,
  `ultimo_cliente_id` int DEFAULT NULL,
  `pagina_inicio` varchar(50) NOT NULL DEFAULT 'dashboard',
  `alias` varchar(80) DEFAULT NULL,
  `ultimo_lugar_expedicion` varchar(200) DEFAULT NULL,
  `sucursal_dir_id` int DEFAULT NULL,
  `ver_botones_detalle` tinyint(1) NOT NULL DEFAULT '1',
  `ver_telefono_detalle` tinyint(1) NOT NULL DEFAULT '1',
  `ver_contacto_detalle` tinyint(1) NOT NULL DEFAULT '1',
  `ver_editado_por_detalle` tinyint(1) NOT NULL DEFAULT '1',
  `ver_panel_estado` tinyint(1) NOT NULL DEFAULT '1',
  `ver_comentario_estado` tinyint(1) NOT NULL DEFAULT '1',
  `ver_panel_evidencia` tinyint(1) NOT NULL DEFAULT '1',
  `ver_comentario_evidencia` tinyint(1) NOT NULL DEFAULT '1',
  `ver_acciones_rapidas` tinyint(1) NOT NULL DEFAULT '1',
  `col_folio` tinyint(1) NOT NULL DEFAULT '1',
  `col_tracking` tinyint(1) NOT NULL DEFAULT '1',
  `col_referencia` tinyint(1) NOT NULL DEFAULT '1',
  `col_cliente` tinyint(1) NOT NULL DEFAULT '1',
  `col_origen` tinyint(1) NOT NULL DEFAULT '1',
  `col_destino` tinyint(1) NOT NULL DEFAULT '1',
  `col_estado` tinyint(1) NOT NULL DEFAULT '1',
  `col_fecha` tinyint(1) NOT NULL DEFAULT '1',
  `auto_activar_cliente` tinyint(1) NOT NULL DEFAULT '0',
  `ver_actualizado_por_detalle` tinyint(1) NOT NULL DEFAULT '1',
  `ver_reimp_por_detalle` tinyint(1) NOT NULL DEFAULT '1',
  `col_autor` tinyint(1) NOT NULL DEFAULT '1',
  `ultimo_documentar` tinyint(1) NOT NULL DEFAULT '0',
  `documentar_activo` tinyint(1) NOT NULL DEFAULT '0',
  `solo_guias_propias` tinyint(1) NOT NULL DEFAULT '0',
  `auto_transito` tinyint(1) NOT NULL DEFAULT '0',
  `puede_editar_historial` tinyint(1) NOT NULL DEFAULT '0',
  `auto_transito_crear` tinyint(1) NOT NULL DEFAULT '0',
  `historial_acceso` tinyint(1) NOT NULL DEFAULT '0',
  `menu_envios` tinyint(1) NOT NULL DEFAULT '1',
  `menu_retrasados` tinyint(1) NOT NULL DEFAULT '1',
  `menu_clientes` tinyint(1) NOT NULL DEFAULT '1',
  `menu_reportes` tinyint(1) NOT NULL DEFAULT '1',
  `menu_configuracion` tinyint(1) NOT NULL DEFAULT '1',
  `menu_historial` tinyint(1) NOT NULL DEFAULT '1',
  `dash_tarjetas` tinyint(1) NOT NULL DEFAULT '1',
  `dash_graficas` tinyint(1) NOT NULL DEFAULT '1',
  `dash_actividad` tinyint(1) NOT NULL DEFAULT '1',
  `sec_envios_filtros` tinyint(1) NOT NULL DEFAULT '1',
  `sec_envios_tabs` tinyint(1) NOT NULL DEFAULT '1',
  `sec_envios_nuevo` tinyint(1) NOT NULL DEFAULT '1',
  `sec_clientes_stats` tinyint(1) NOT NULL DEFAULT '1',
  `sec_clientes_filtros` tinyint(1) NOT NULL DEFAULT '1',
  `sec_clientes_nuevo` tinyint(1) NOT NULL DEFAULT '1',
  `sec_reportes_stats` tinyint(1) NOT NULL DEFAULT '1',
  `sec_reportes_filtros` tinyint(1) NOT NULL DEFAULT '1',
  `sec_retrasados_stats` tinyint(1) NOT NULL DEFAULT '1',
  `sec_retrasados_filtros` tinyint(1) NOT NULL DEFAULT '1',
  `sec_usuarios_stats` tinyint(1) NOT NULL DEFAULT '1',
  `sec_usuarios_filtros` tinyint(1) NOT NULL DEFAULT '1',
  `sec_envios_editar` tinyint(1) NOT NULL DEFAULT '1',
  `sec_usuarios_nuevo` tinyint(1) NOT NULL DEFAULT '1',
  `sec_reportes_general` tinyint(1) NOT NULL DEFAULT '1',
  `sec_reportes_clientes` tinyint(1) NOT NULL DEFAULT '1',
  `sec_reportes_periodo` tinyint(1) NOT NULL DEFAULT '1',
  `sec_reportes_rendimiento` tinyint(1) NOT NULL DEFAULT '1',
  `perfil_impresora_id` int DEFAULT NULL,
  `menu_usuarios` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `fk_usuario_cliente` (`cliente_id`),
  CONSTRAINT `usuarios_ibfk_1` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

